version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=YourPasswordHere1234
      - JUDGE0=http://judge0-server-1:2358
      - PRISMA_INTROSPECTION_ENGINE_BINARY=/usr/src/app/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x
      - PRISMA_QUERY_ENGINE_BINARY=/usr/src/app/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node
      - PRISMA_FMT_BINARY=/usr/src/app/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - shared-network 
         

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend  
    networks:
      - shared-network

 
networks:
  shared-network:
    external: true     